Repository Azure/Azure-Proactive-Resiliency-Library-v2, pull requests merged in 2024-09, with the labels that each got.

#385 fix: Fix/devsync
  docs/content/tools/collector/_index.md
  tools/1_wara_collector.ps1
  tools/2_wara_data_analyzer.ps1
Labels: Bug :lady_beetle:

#318 feat: SAP recommendations added
  azure-specialized-workloads/sap/kql/4884cada-b9c7-42d5-8153-3853e4a6f6c4.kql
  azure-specialized-workloads/sap/kql/697deb1d-d398-4989-9734-9e6c18f7e0ad.kql
  azure-specialized-workloads/sap/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:, Needs: Author Feedback :ear:

#380 feat: Add TTL recommendation for DNS zones
  azure-resources/Network/dnsZones/_index.md
  azure-resources/Network/dnsZones/kql/7d09523b-b3c0-403e-b104-d5d46240d683.kql
  azure-resources/Network/dnsZones/recommendations.yaml
  azure-resources/Network/privateDnsZones/kql/3538aa48-c40b-455b-a93b-269fe6e65be2.kql
  azure-resources/Network/privateDnsZones/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:

#263 feat: Line-breaks in learnMoreLink URLs
  tools/2_wara_data_analyzer.ps1
Labels: Enhancement :new:, Needs: Attention from aprl-wara-tools :wave:, Area: Tools :toolbox:

#262 fix: Fix duplicated "Microsoft." in resource type in output messages
  tools/1_wara_collector.ps1
Labels: Bug :lady_beetle:, Needs: Attention from aprl-wara-tools :wave:, Area: Tools :toolbox:

#395 fix: Fix typo
  azure-resources/Network/privateDnsZones/recommendations.yaml
Labels: Bug :lady_beetle:

#400 fix: Fix typo (add period)
  azure-specialized-workloads/sap/recommendations.yaml
Labels: Bug :lady_beetle:

#407 feat: Add guid to pages
  docs/layouts/shortcodes/azure-resources-recommendationlist.html
  docs/layouts/shortcodes/azure-specialized-workloads-recommendationlist.html
  docs/layouts/shortcodes/azure-waf-recommendationlist.html
Labels: Enhancement :new:, Area: Hugo :computer:, Auto-Merge :heavy_check_mark:

#405 docs: update service bus AZ recommendation
  azure-resources/ServiceBus/namespaces/kql/20057905-262c-49fe-a9be-49f423afb359.kql
  azure-resources/ServiceBus/namespaces/kql/20057905-262c-49fe-a9be-49f423afb359.kql.upstream-dependency
  azure-resources/ServiceBus/namespaces/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Area: Resource Graph Query(s) :hash:

#397 fix: Fix 'n/a' resource id handing in resource type counting
  tools/3_wara_reports_generator.ps1
Labels: Bug :lady_beetle:, Needs: Attention from aprl-wara-tools :wave:

#403 fix: Fix Azure Boost recommendation description
  azure-resources/Compute/virtualMachines/recommendations.yaml
Labels: Bug :lady_beetle:

#409 fix: Removing VPN as a failover option for ExpressRoute Circuits - critical workloads should all use dual Circuits.
  azure-resources/Network/expressRouteCircuits/kql/f902cf86-2b53-2942-abc2-781f4fb62be6.kql
  azure-resources/Network/expressRouteCircuits/recommendations.yaml
Labels: Bug :lady_beetle:, Area: Resource Guidance :memo:, Auto-Merge :heavy_check_mark:

#408 docs: Updating impact of AVD multi-region items
  azure-specialized-workloads/avd/recommendations.yaml
Labels: Area: Resource Guidance :memo:

#417 feat: Added AZ recommendation for Cosmos DB
  azure-resources/DocumentDB/databaseAccounts/kql/921631f6-ed59-49a5-94c1-f0f3ececa580.kql
  azure-resources/DocumentDB/databaseAccounts/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:, Area: Resource Graph Query(s) :hash:, PR: Safe to Test ARG Queries :test_tube:

#422 feat: Recommendation Object Pipeline
  .github/scripts/build-recommendation-object.ps1
  .github/workflows/build-recommendation-object.yml
Labels: Enhancement :new:, Area: Tools :toolbox:

#421 docs: add sql failover group endpoint recommendation
  azure-resources/Sql/servers/kql/de266d8a-a9f3-4cb9-be95-9306001fceea.kql
  azure-resources/Sql/servers/recommendations.yaml
Labels: Area: Resource Guidance :memo:

#424 fix: recommendation object pipeline
  .github/scripts/build-recommendation-object.ps1
  .github/workflows/build-recommendation-object.yml
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#426 feat: Updated impact of two medium AVS/privateCloud recommendations to high.
  azure-resources/AVS/privateClouds/recommendations.yaml
Labels: Enhancement :new:, Auto-Merge :heavy_check_mark:

#433 fix: add write permission to pipeline
  .github/workflows/build-recommendation-object.yml
Labels: Bug :lady_beetle:, Area: Tools :toolbox:

#419 feat: [Analyzer] Add RepoUrl parameter for custom ARPL repo
  tools/2_wara_data_analyzer.ps1
Labels: Enhancement :new:, Needs: Attention from aprl-wara-tools :wave:

#418 feat: [Collector] Add RepoUrl parameter for custom ARPL repo
  tools/1_wara_collector.ps1
Labels: Enhancement :new:, Needs: Attention from aprl-wara-tools :wave:

#416 fix: Fix regression on line-breaks in LearnMore column
  tools/2_wara_data_analyzer.ps1
Labels: Bug :lady_beetle:, Needs: Attention from aprl-wara-tools :wave:

#440 feat: improves queries that check zone redundancy by adding a Where clause with the regions with AZ
  azure-resources/ApiManagement/service/kql/740f2c1c-8857-4648-80eb-47d2c56d5a50.kql
  azure-resources/ApiManagement/service/kql/baf3bfc0-32a2-4c0c-926d-c9bf0b49808e.kql
  azure-resources/App/managedEnvironments/kql/f4201965-a88d-449d-b3b4-021394719eb2.kql
  azure-resources/Cache/Redis/kql/5a44bd30-ae6a-4b81-9b68-dc3a8ffca4d8.kql
  azure-resources/CognitiveServices/_index.md
  azure-resources/CognitiveServices/accounts/_index.md
  azure-resources/CognitiveServices/accounts/recommendations.yaml
  azure-resources/Compute/galleries/kql/488dcc8b-f2e3-40ce-bf95-73deb2db095f.kql
  azure-resources/Compute/virtualMachineScaleSets/kql/1422c567-782c-7148-ac7c-5fc14cf45adc.kql
  azure-resources/Compute/virtualMachines/kql/2bd0be95-a825-6f47-a8c6-3db1fb5eb387.kql
  azure-resources/Compute/virtualMachines/kql/fa0cf4f5-0b21-47b7-89a9-ee936f193ce1.kql
  azure-resources/ContainerRegistry/registries/kql/63491f70-22e4-3b4a-8b0c-845450e46fac.kql
  azure-resources/ContainerService/managedClusters/kql/4f63619f-5001-439c-bacb-8de891287727.kql
  azure-resources/DBforMySQL/flexibleServers/kql/88856605-53d8-4bbd-a75b-4a7b14939d32.kql
  azure-resources/DBforPostgreSQL/flexibleServers/kql/ca87914f-aac4-4783-ab67-82a6f936f194.kql
  azure-resources/NetApp/netAppAccounts/kql/47d100a5-7f85-5742-967a-67eb5081240a.kql
  azure-resources/NetApp/netAppAccounts/kql/e3d742e1-dacd-9b48-b6b1-510ec9f87c96.kql
  azure-resources/Network/applicationGateways/kql/c9c00f2a-3888-714b-a72b-b4c9e8fcffb2.kql
  azure-resources/Network/azureFirewalls/kql/c72b7fee-1fa0-5b4b-98e5-54bcae95bb74.kql
  azure-resources/Network/loadBalancers/kql/621dbc78-3745-4d32-8eac-9e65b27b7512.kql
  azure-resources/Network/publicIPAddresses/kql/c63b81fb-7afc-894c-a840-91bb8a8dcfaf.kql
  azure-resources/Network/virtualNetworkGateways/kql/4bae5a28-5cf4-40d9-bcf1-623d28f6d917.kql
  azure-resources/Network/virtualNetworkGateways/kql/5b1933a6-90e4-f642-a01f-e58594e5aab2.kql
  azure-resources/Network/virtualNetworkGateways/kql/bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql
  azure-resources/SignalRService/signalR/kql/6a8b3db9-5773-413a-a127-4f7032f34bbd.kql
  azure-resources/Sql/servers/kql/c0085c32-84c0-c247-bfa9-e70977cbf108.kql
  azure-resources/Storage/storageAccounts/kql/e6c7e1cc-2f47-264d-aa50-1da421314472.kql
  azure-resources/Web/serverFarms/kql/88cb90c2-3b99-814b-9820-821a63f600dd.kql
Labels: Enhancement :new:
