Repository Azure/Azure-Proactive-Resiliency-Library-v2, pull requests merged in 2024-11, with the labels that each got.

#497 fix: Updating WAF recommendations and WARA in ScopCSV file
  .github/scripts/build-recommendation-object.ps1
  .github/workflows/build-recommendation-object.yml
  azure-waf/reliability/recommendations.yaml
  tools/WARAinScopeResTypes.csv
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#480 fix: Update Databricks Recommendation List - AB36089
  azure-resources/Databricks/workspaces/kql/892ca809-e2b5-9a47-924a-71132bf6f902.kql
  azure-resources/Databricks/workspaces/kql/c166602e-0804-e34b-be8f-09b4d56e1fcd.kql
  azure-resources/Databricks/workspaces/kql/e94da1f8-33e7-48a6-b301-72f19a53bc29.kql
  azure-resources/Databricks/workspaces/recommendations.yaml
Labels: Bug :lady_beetle:, Area: Resource Guidance :memo:

#504 fix: recommendation automation value
  azure-resources/Compute/galleries/recommendations.yaml
  azure-resources/EventHub/namespaces/kql/84636c6c-b317-4722-b603-7b1ffc16384b.kql
  azure-resources/Network/networkWatchers/recommendations.yaml
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#501 refactor: Adjust permissions scope for build object recommendation workflow
  .github/workflows/build-recommendation-object.yml
  .github/workflows/validate-queries.yml
Labels: Type: Hygiene :broom:, Auto-Merge :heavy_check_mark:

#509 fix: blank lines in impactedresources column
  tools/2_wara_data_analyzer.ps1
  tools/Version.json
Labels: Bug :lady_beetle:

#511 fix: Update Virtual Network Gateway query and add new query for TrafficManagerProfiles
  azure-resources/Network/trafficManagerProfiles/kql/1ad9d7b7-9692-1441-a8f4-93792efbe97a.kql
  azure-resources/Network/trafficManagerProfiles/recommendations.yaml
  azure-resources/Network/virtualNetworkGateways/kql/bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql
  tools/data/recommendations.json
Labels: Bug :lady_beetle:, Auto-Merge :heavy_check_mark:

#513 fix: Adjust workflow to require environment approval of PR before running specific workflows
  .github/workflows/build-recommendation-object.yml
  .github/workflows/validate-queries.yml
Labels: Bug :lady_beetle:, Type: Hygiene :broom:

#443 docs: APIM recommendations are PG verified now and updates for stv1 retirement
  azure-resources/ApiManagement/service/recommendations.yaml
  tools/data/recommendations.json
Labels: Enhancement :new:, Needs: Attention from aprl-maintainers :wave:

#505 docs: App Service pg feedback
  azure-resources/Web/serverFarms/recommendations.yaml
  tools/data/recommendations.json
Labels: Area: Resource Guidance :memo:, Needs: Attention from aprl-maintainers :wave:

#519 fix: service health recommendation query
  azure-resources/Subscription/subscriptions/kql/9729c89d-8118-41b4-a39b-e12468fa872b.kql
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#512 docs: PG Sign off completed for two remaining VM recommendations. Change Impact from Low to Medium for one of those two recommendations as well.
  azure-resources/Compute/virtualMachines/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Needs: Attention from aprl-maintainers :wave:

#479 feat: Key Vault RBAC recommendation updates
  azure-resources/KeyVault/vaults/recommendations.yaml
  tools/data/recommendations.json
Labels: Area: Resource Guidance :memo:, Enhancement :new:, Area: Resource Graph Query(s) :hash:

#522 fix: move TM recommendation to correct resource type
  azure-resources/Cdn/profiles/recommendations.yaml
  azure-resources/Network/trafficManagerProfiles/kql/9437634c-d69e-2747-b13e-631c13182150.kql
  azure-resources/Network/trafficManagerProfiles/recommendations.yaml
Labels: Bug :lady_beetle:

#527 fix: advisor issues and analyzer updates
  tools/1_wara_collector.ps1
  tools/2_wara_data_analyzer.ps1
  tools/Version.json
Labels: Bug :lady_beetle:

#530 docs: move disk recommendations to correct resource type
  azure-resources/Compute/disks/_index.md
  azure-resources/Compute/disks/kql/3263a64a-c256-de48-9818-afd3cbc55c2a.kql
  azure-resources/Compute/disks/kql/fa0cf4f5-0b21-47b7-89a9-ee936f193ce1.kql
  azure-resources/Compute/disks/recommendations.yaml
  azure-resources/Compute/virtualMachines/recommendations.yaml
Labels: Bug :lady_beetle:, Area: Resource Guidance :memo:

#523 fix: move RG recommendation to correct resource type
  azure-resources/Resources/resourceGroups/_index.md
  azure-resources/Resources/subscriptions/_index.md
  azure-resources/Resources/subscriptions/kql/98bd7098-49d6-491b-86f1-b143d6b1a0ff.kql
  azure-resources/Resources/subscriptions/recommendations.yaml
Labels: Bug :lady_beetle:, Needs: Attention from aprl-maintainers :wave:

#515 feat: NATGW Recommendations Update PG Signoff changes
  azure-resources/Network/natGateways/kql/419df1ea-336b-460a-b6b2-fefe2588fcef.kql
  azure-resources/Network/natGateways/kql/4281631c-3d19-4994-8d96-084c2a51a534.kql
  azure-resources/Network/natGateways/recommendations.yaml
  tools/data/recommendations.json
Labels: Enhancement :new:

#531 docs: disable all non-reliability recommendations
  azure-resources/Cdn/profiles/recommendations.yaml
  azure-resources/Compute/galleries/recommendations.yaml
  azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml
  azure-resources/Compute/virtualMachines/recommendations.yaml
  azure-resources/DocumentDB/databaseAccounts/recommendations.yaml
  azure-resources/KeyVault/vaults/recommendations.yaml
  azure-resources/NetApp/netAppAccounts/recommendations.yaml
  azure-resources/Network/applicationGateways/recommendations.yaml
  azure-resources/Network/azureFirewalls/recommendations.yaml
  azure-resources/Network/expressRouteCircuits/recommendations.yaml
  azure-resources/Network/frontDoorWebApplicationFirewallPolicies/recommendations.yaml
  azure-resources/Network/privateDnsZones/recommendations.yaml
  azure-resources/Network/trafficManagerProfiles/recommendations.yaml
  azure-resources/Network/virtualNetworks/recommendations.yaml
  azure-resources/Sql/servers/recommendations.yaml
  azure-resources/Storage/storageAccounts/recommendations.yaml
  azure-resources/Subscription/subscriptions/recommendations.yaml
  tools/data/recommendations.json
Labels: Area: Resource Guidance :memo:, Needs: Attention from aprl-maintainers :wave:

#525 docs: delete classic stg recommendation
  azure-resources/Storage/storageAccounts/kql/63ad027e-611c-294b-acc5-8e3234db9a40.kql
  azure-resources/Storage/storageAccounts/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Needs: Attention from aprl-maintainers :wave:
