Repository Azure/Azure-Proactive-Resiliency-Library-v2, pull requests merged in 2025-01, with the labels that each got.

#602 fix: recommendation obj
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#578 docs: reccomendation cross-region failover for Private DNS Resolver
  azure-resources/Network/dnsResolvers/kql/bdd38c02-96bf-4d4e-a636-293729463f3d.kql
  azure-resources/Network/dnsResolvers/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Area: Resource Graph Query(s) :hash:, Needs: Attention from aprl-networking :wave:

#591 docs: APRL recommendations for AOAI
  azure-resources/CognitiveServices/accounts/kql/042c034e-2b85-4c1d-bf9a-65c75a6b43e9.kql
  azure-resources/CognitiveServices/accounts/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:, Needs: Attention from aprl-maintainers :wave:

#577 docs: Added new APRL recommendations for App Insights for Machine learning
  azure-resources/Insights/dataCollectionEndpoints/_index.md
  azure-specialized-workloads/ai/kql/47176883-2602-455b-97f0-6c6a371bf928.kql
  azure-specialized-workloads/ai/kql/89928e61-bba8-4c25-99c5-a06a09849ecc.kql
  azure-specialized-workloads/ai/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Needs: Attention from aprl-maintainers :wave:

#597 fix: fix on filtering recommendations
  tools/2_wara_data_analyzer.ps1
  tools/Version.json
Labels: Bug :lady_beetle:, Needs: Attention from aprl-wara-tools :wave:

#585 docs: New Aprl recommendations for CognitiveServices/Accounts & MachineLearningservices/Workspaces
  azure-resources/CognitiveServices/accounts/kql/72b1b4ad-a14b-4430-9799-91bda782973d.kql
  azure-resources/CognitiveServices/accounts/recommendations.yaml
  azure-resources/MachineLearningServices/workspaces/kql/98f15850-f31e-4fb2-8874-74f5aabbcf91
  azure-resources/MachineLearningServices/workspaces/recommendations.yaml
  azure-specialized-workloads/ai/_index.md
Labels: Enhancement :new:, Needs: Attention from aprl-maintainers :wave:, Auto-Merge :heavy_check_mark:

#604 fix: Fix Azure DNS Private Resolver recommendation
  azure-resources/Network/dnsResolvers/recommendations.yaml
Labels: Bug :lady_beetle:

#608 fix: Fix YAML file formatting style consistency
  azure-resources/CognitiveServices/accounts/recommendations.yaml
  azure-resources/MachineLearningServices/workspaces/recommendations.yaml
  azure-resources/Network/expressRouteGateways/recommendations.yaml
  azure-resources/Network/p2sVpnGateways/recommendations.yaml
  azure-resources/Network/virtualHubs/recommendations.yaml
  azure-resources/Network/vpnGateways/recommendations.yaml
Labels: Bug :lady_beetle:

#606 fix: Virtual Network Gateway (bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql) returns resId instead of id
  azure-resources/Network/virtualNetworkGateways/kql/bbe668b7-eb5c-c746-8b82-70afdedf0cae.kql
Labels: Bug :lady_beetle:

#607 docs: added reference to availability zone for app service plans
  azure-specialized-workloads/ai/_index.md
Labels: Area: Resource Guidance :memo:

#611 fix: fix on filtering ImpactedResources
  azure-resources/Web/serverFarms/recommendations.yaml
  tools/2_wara_data_analyzer.ps1
  tools/Version.json
Labels: Bug :lady_beetle:

#586 docs: Added new recommendations for Azure bastion hosts
  azure-resources/Network/bastionHosts/_index.md
  azure-resources/Network/bastionHosts/kql/0e57956d-71d9-4a35-bdcf-d7cfd7cd71f4.kql
  azure-resources/Network/bastionHosts/kql/c9b0c6f6-1f64-4b4b-8165-00770b295dd7.kql
  azure-resources/Network/bastionHosts/recommendations.yaml
  azure-specialized-workloads/ai/_index.md
Labels: Enhancement :new:, Needs: Attention from aprl-maintainers :wave:, Needs: Attention :wave:

#619 fix: remove recommendationTypeId value for VM AZ recommendation
  azure-resources/Compute/virtualMachines/recommendations.yaml
Labels: Bug :lady_beetle:

#618 refactor: Limit learnmorelink to one link per recommendation
  .github/scripts/schemas/aprl-schema.yaml
  azure-resources/AVS/privateClouds/recommendations.yaml
  azure-resources/ApiManagement/service/recommendations.yaml
  azure-resources/Automation/automationAccounts/recommendations.yaml
  azure-resources/Cdn/profiles/recommendations.yaml
  azure-resources/Compute/disks/recommendations.yaml
  azure-resources/Compute/galleries/recommendations.yaml
  azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml
  azure-resources/Compute/virtualMachines/recommendations.yaml
  azure-resources/ContainerRegistry/registries/recommendations.yaml
  azure-resources/ContainerService/managedClusters/recommendations.yaml
  azure-resources/Dashboard/grafana/recommendations.yaml
  azure-resources/Databricks/workspaces/recommendations.yaml
  azure-resources/Devices/iotHubs/recommendations.yaml
  azure-resources/DocumentDB/databaseAccounts/recommendations.yaml
  azure-resources/Insights/activityLogAlerts/recommendations.yaml
  azure-resources/MachineLearningServices/workspaces/recommendations.yaml
  azure-resources/NetApp/netAppAccounts/recommendations.yaml
  azure-resources/Network/applicationGateways/recommendations.yaml
  azure-resources/Network/azureFirewalls/recommendations.yaml
  azure-resources/Network/expressRouteCircuits/recommendations.yaml
  azure-resources/Network/expressRoutePorts/recommendations.yaml
  azure-resources/Network/frontDoorWebApplicationFirewallPolicies/recommendations.yaml
  azure-resources/Network/loadBalancers/recommendations.yaml
  azure-resources/Network/natGateways/recommendations.yaml
  azure-resources/Network/publicIPAddresses/recommendations.yaml
  azure-resources/Network/trafficManagerProfiles/recommendations.yaml
  azure-resources/Network/virtualNetworkGateways/recommendations.yaml
  azure-resources/Network/virtualNetworks/recommendations.yaml
  azure-resources/OperationalInsights/workspaces/recommendations.yaml
  azure-resources/RecoveryServices/vaults/recommendations.yaml
  azure-resources/ServiceBus/namespaces/recommendations.yaml
  azure-resources/Sql/servers/recommendations.yaml
  azure-resources/Storage/storageAccounts/recommendations.yaml
  azure-resources/Subscription/subscriptions/recommendations.yaml
  azure-resources/VirtualMachineImages/imageTemplates/recommendations.yaml
  azure-resources/Web/serverFarms/recommendations.yaml
  azure-resources/Web/sites/recommendations.yaml
  azure-specialized-workloads/ai/recommendations.yaml
  azure-specialized-workloads/avd/recommendations.yaml
  azure-specialized-workloads/avs/recommendations.yaml
  azure-specialized-workloads/sap/recommendations.yaml
Labels: Enhancement :new:

#623 fix: Remove low relevant learn more link
  azure-resources/Network/bastionHosts/recommendations.yaml
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#622 fix: Fix duplicated slash in URL
  azure-resources/Storage/storageAccounts/recommendations.yaml
  tools/data/recommendations.json
Labels: Bug :lady_beetle:

#632 fix: fix on filtering resourcetypes on ImpactedResources
  tools/2_wara_data_analyzer.ps1
  tools/Version.json
Labels: Bug :lady_beetle:

#631 fix: ExpressRoute gateways recommendation
  azure-resources/Network/expressRouteGateways/recommendations.yaml
Labels: Bug :lady_beetle:

#630 fix: YAML format styling - Virtual hubs
  azure-resources/Network/virtualHubs/recommendations.yaml
Labels: Bug :lady_beetle:

#629 fix: YAML format styling - VPN sites
  azure-resources/Network/vpnSites/recommendations.yaml
Labels: Bug :lady_beetle:

#627 docs: aisearch resiliency recommendations
  azure-resources/Search/searchServices/kql/b376281d-bfec-4695-8f90-9a44544fdfa4.kql
  azure-resources/Search/searchServices/kql/dff62efe-c3a3-4621-98b3-c877c65cb195.kql
  azure-resources/Search/searchServices/recommendations.yaml
  azure-specialized-workloads/ai/kql/a6c8f3f3-199a-4a13-aaf0-eb51eed5352e.kql
  azure-specialized-workloads/ai/recommendations.yaml
Labels: Auto-Merge :heavy_check_mark:, Type: Resource or Feature Deprecation :ghost:

#640 fix: Fix recommendation tags
  azure-resources/Search/searchServices/recommendations.yaml
  azure-specialized-workloads/ai/recommendations.yaml
Labels: Bug :lady_beetle:

#639 fix: Add AI tags
  azure-resources/ApiManagement/service/recommendations.yaml
  azure-resources/Batch/batchAccounts/recommendations.yaml
  azure-resources/CognitiveServices/accounts/recommendations.yaml
  azure-resources/MachineLearningServices/registries/recommendations.yaml
  azure-resources/MachineLearningServices/workspaces/recommendations.yaml
  azure-resources/Network/bastionHosts/recommendations.yaml
Labels: Bug :lady_beetle:, Auto-Merge :heavy_check_mark:
