Repository Azure/Azure-Proactive-Resiliency-Library-v2, pull requests merged in 2025-02, with the labels that each got.

#649 feat: Add WAF Tag to schema and update WAF recommendations with tag
  .github/scripts/schemas/aprl-schema.yaml
  azure-resources/Network/bastionHosts/recommendations.yaml
  azure-resources/Network/dnsResolvers/recommendations.yaml
  azure-resources/Search/searchServices/recommendations.yaml
  azure-specialized-workloads/ai/recommendations.yaml
  azure-waf/reliability/recommendations.yaml
Labels: Enhancement :new:

#654 docs: add preview tools documentation
  docs/content/tools-preview/_index.md
  docs/content/tools-preview/analyzer/_index.md
  docs/content/tools-preview/collector/_index.md
  docs/content/tools-preview/reports/_index.md
Labels: Enhancement :new:

#651 feat: App Insights Regional Endpoint Connection String Recommendation
  azure-resources/Insights/components/kql/092f5c85-bffb-48b0-b85d-d543c6b54800.kql
  azure-resources/Insights/components/recommendations.yaml
Labels: Enhancement :new:

#656 fix: Fix recommendation YAML style
  azure-resources/Insights/components/recommendations.yaml
Labels: Bug :lady_beetle:, Auto-Merge :heavy_check_mark:

#658 docs: Update _index.md
  docs/content/tools/collector/_index.md
Labels: Area: Tools :toolbox:

#652 feat: disable AKS auto-scale subnet size rec
  azure-resources/ContainerService/managedClusters/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:

#661 feat: Remove "en-us" locale identifier from URLs (#642)
  azure-resources/AAD/domainServices/recommendations.yaml
  azure-resources/AVS/privateClouds/recommendations.yaml
  azure-resources/ApiManagement/service/recommendations.yaml
  azure-resources/App/managedEnvironments/recommendations.yaml
  azure-resources/AppConfiguration/configurationStores/recommendations.yaml
  azure-resources/Automation/automationAccounts/recommendations.yaml
  azure-resources/Cache/Redis/recommendations.yaml
  azure-resources/Cdn/profiles/recommendations.yaml
  azure-resources/CognitiveServices/accounts/recommendations.yaml
  azure-resources/Compute/galleries/recommendations.yaml
  azure-resources/Compute/virtualMachineScaleSets/recommendations.yaml
  azure-resources/Compute/virtualMachines/recommendations.yaml
  azure-resources/ContainerRegistry/registries/recommendations.yaml
  azure-resources/ContainerService/managedClusters/recommendations.yaml
  azure-resources/DBforMySQL/flexibleServers/recommendations.yaml
  azure-resources/DBforPostgreSQL/flexibleServers/recommendations.yaml
  azure-resources/Databricks/workspaces/recommendations.yaml
  azure-resources/DesktopVirtualization/hostPools/recommendations.yaml
  azure-resources/Devices/iotHubs/recommendations.yaml
  azure-resources/DocumentDB/databaseAccounts/recommendations.yaml
  azure-resources/EventGrid/topics/recommendations.yaml
  azure-resources/Insights/activityLogAlerts/recommendations.yaml
  azure-resources/MachineLearningServices/registries/recommendations.yaml
  azure-resources/MachineLearningServices/workspaces/recommendations.yaml
  azure-resources/NetApp/netAppAccounts/recommendations.yaml
  azure-resources/Network/applicationGateways/recommendations.yaml
  azure-resources/Network/azureFirewalls/recommendations.yaml
  azure-resources/Network/bastionHosts/recommendations.yaml
  azure-resources/Network/connections/recommendations.yaml
  azure-resources/Network/ddosProtectionPlans/recommendations.yaml
  azure-resources/Network/expressRouteCircuits/recommendations.yaml
  azure-resources/Network/expressRouteGateways/recommendations.yaml
  azure-resources/Network/expressRoutePorts/recommendations.yaml
  azure-resources/Network/loadBalancers/recommendations.yaml
  azure-resources/Network/natGateways/recommendations.yaml
  azure-resources/Network/networkWatchers/recommendations.yaml
  azure-resources/Network/p2sVpnGateways/recommendations.yaml
  azure-resources/Network/privateDnsZones/recommendations.yaml
  azure-resources/Network/publicIPAddresses/recommendations.yaml
  azure-resources/Network/routeTables/recommendations.yaml
  azure-resources/Network/virtualHubs/recommendations.yaml
  azure-resources/Network/virtualNetworkGateways/recommendations.yaml
  azure-resources/Network/vpnGateways/recommendations.yaml
  azure-resources/Network/vpnSites/recommendations.yaml
  azure-resources/NetworkFunction/azureTrafficCollectors/recommendations.yaml
  azure-resources/RecoveryServices/vaults/recommendations.yaml
  azure-resources/Search/searchServices/recommendations.yaml
  azure-resources/ServiceBus/namespaces/recommendations.yaml
  azure-resources/Sql/servers/recommendations.yaml
  azure-resources/Storage/storageAccounts/recommendations.yaml
  azure-resources/Subscription/subscriptions/recommendations.yaml
  azure-resources/VirtualMachineImages/imageTemplates/recommendations.yaml
  azure-resources/Web/serverFarms/recommendations.yaml
  azure-resources/Web/sites/recommendations.yaml
  azure-specialized-workloads/ai/recommendations.yaml
  azure-specialized-workloads/avs/recommendations.yaml
  azure-specialized-workloads/hpc/recommendations.yaml
  azure-specialized-workloads/sap/recommendations.yaml
  azure-waf/reliability/recommendations.yaml
  docs/content/contributing/create-content/create-recommendations/_index.md
Labels: Enhancement :new:

#638 feat: add sql failover group customer managed policy recommendation (v2)
  azure-resources/Sql/servers/kql/0f838324-ffe3-4b8a-b7a2-d983be8f9fa9.kql
  azure-resources/Sql/servers/recommendations.yaml
Labels: Enhancement :new:

#662 feat: disable AKS Azure Linux recommendation
  azure-resources/ContainerService/managedClusters/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:

#669 feat: update of AI-GPT tagging
  azure-resources/ApiManagement/service/recommendations.yaml
  azure-resources/Batch/batchAccounts/recommendations.yaml
  azure-resources/CognitiveServices/accounts/recommendations.yaml
  azure-resources/MachineLearningServices/registries/recommendations.yaml
  azure-resources/MachineLearningServices/workspaces/recommendations.yaml
  azure-resources/Network/bastionHosts/recommendations.yaml
  azure-specialized-workloads/ai/recommendations.yaml
Labels: Enhancement :new:
