Repository Azure/Azure-Proactive-Resiliency-Library-v2, pull requests merged in 2025-03, with the labels that each got.

#670 docs: add expert analysis spreadsheet steps
  docs/content/tools-preview/_index.md
  docs/content/tools-preview/analyzer/_index.md
Labels: Area: Tools :toolbox:

#674 fix: updating CSV File with correct Azure Service Friendly names
  tools/Optional - Assessment Report - Template.docx
  tools/WARAinScopeResTypes.csv
Labels: Bug :lady_beetle:

#678 feat: disable VM monitor agent rec
  azure-resources/Compute/virtualMachines/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:

#683 feat: Add HCX snapshot recommendation
  azure-specialized-workloads/avs/kql/1f25a3d8-ac67-4b84-96c5-9304bfa8a164.kql
  azure-specialized-workloads/avs/recommendations.yaml
Labels: Area: Resource Guidance :memo:, Enhancement :new:

#691 fix: disabled bad recommendation
  azure-resources/Cdn/profiles/recommendations.yaml
Labels: Bug :lady_beetle:
